### ISSUE TITLE
 twitch-title.py change for TMI

### ISSUE THREAD

**Issue by internectual** [Poorchop/hexchat-scripts#7]
if chan.type == 2 and chan.context.get_info("host") == "irc.twitch.tv":

change to:

    if chan.type == 2 and chan.context.get_info("server") == "tmi.twitch.tv":

and

    hexchat.command("RECV :Topic!Topic@twitch.tv TOPIC #{0} :{1}".format(self.channel, msg))

change to:

    hexchat.command("RECV :{0}!Topic@twitch.tv TOPIC #{0} :{1}".format(self.channel, msg))

The first change was to resolve an issue I had from connecting to my ZNC "host" returned the hostname of the ZNC box, and "tmi.twitch.tv" is the faux IRC server for Twitch chat now. Without the change the script wouldn't work at all. Second change was just so the "user" was the channel name instead of "Topic" for purely aesthetic reasons.

also another change:

    server = hexchat.get_info("host")

to

    server = hexchat.get_info("server")

**Comment by internectual** [comment]
also another change:
    server = hexchat.get_info("host")
to
    server = hexchat.get_info("server")

**Comment by internectual** [comment]
Also, I'm wondering if you wouldn't mind changing the behavior of your script to keep a history of the last topic and not setting it if unchanged. Every 10 minutes the fake /topic change spams the channel tab and it's particularly annoying in ones for offline streams with little to no other activity, not to mention increasing log size needlessly (if enabled).

If a dupe check is implemented the frequency of checks could be increased with minimal impact.

**Comment by Poorchop** [comment]
>Also, I'm wondering if you wouldn't mind changing the behavior of your script to keep a history of the last topic and not setting it if unchanged.

Looking over the script, it seems like I sort of already do this with regards to setting the topic, but I still print the message in the channel tab itself every 10 minutes. I guess this is what you're referring to. My initial idea was to just be reminded about channels regardless of whether or not anything changed, but your idea makes more sense. I think it should just be a matter of moving line 35 to line 41.

As for the other changes, thanks for the heads up. I guess I forgot to update this script when I switched to ZNC.

For the record, this script is sort of fundamentally broken and I meant to completely rewrite it a really long time ago, but I never took the time to do it. I might get around to it at some point hopefully.

**Comment by Poorchop** [comment]
I don't really ever use Twitch chat so maybe you can test out the [patched version](https://github.com/Poorchop/hexchat-scripts/blob/dev/twitch-title.py) in the dev branch and let me know if this is what you want.

**Comment by internectual** [comment]
The patched version doesn't fix the topic spam. I don't think

    if hexchat.get_info("topic") != msg:

is ever evaluating "false". I think it might be an issue with what get_info is returning.

**Comment by Poorchop** [comment]
Thanks for testing this. I added a dirty workaround for now but it's not a permanent solution - I might be able to add another small fix but I might try rewriting the script first.

**Comment by internectual** [comment]
It still fires off a "Topic Change" event every 10 minutes even if the channel/stream status is unchanged.

**Comment by Poorchop** [comment]
I started rewriting the script. The channel message and topic spam isn't an issue anymore and it works as intended for the most part.

The main issue now is that there are some weird context and timing issues with threading in HexChat. I don't know if I can do much about the timing issue, but right now I'm trying to decide where I want to print the messages and whether or not it's actually safe to fetch stream information immediately after joining a new channel.

The changes are still in the dev branch. I tested for a while and didn't notice any issues, so you can start using it now if you want.

**Comment by internectual** [comment]
I do miss the join_cb. It was fine before, though I'm not sure what your criteria for "safe" is. I just changed the check from 600 to 60 to compensate. The Topic Change spam is fixed and everything else seems to be working well.

**Comment by Poorchop** [comment]
It should be possible to make the join behavior work as before, I just need to think about how I want to do it. I just don't want to drop it in the same way that I had it before because I don't want to have two separate callbacks trying to modify the same object, which might happen since there's a reoccurring threaded process.

I pushed another few small changes, so everything should be finished except for this one feature.
